name: eschaton
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: Issac <email@example.com>

environment:
  sdk: '>=2.8.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner:
  build_web_compilers:

web:
  compiler:
    debug: dartdevc
